import type { Methodology } from '../types/stock';

/**
 * Captures a DOM element as a multi-page PDF using html2canvas + jspdf.
 * Elements with class `.no-print` are hidden during capture.
 */
export async function exportPdf(
  element: HTMLElement,
  methodology: Methodology,
  tickers: string[]
): Promise<void> {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import('html2canvas'),
    import('jspdf'),
  ]);

  // Hide no-print elements during capture
  const noPrintEls = element.querySelectorAll<HTMLElement>('.no-print');
  noPrintEls.forEach((el) => (el.style.display = 'none'));

  const canvas = await html2canvas(element, {
    backgroundColor: '#0a0e1a',
    scale: 2,
    useCORS: true,
    logging: false,
    windowWidth: 1200,
  });

  // Restore hidden elements
  noPrintEls.forEach((el) => (el.style.display = ''));

  const imgData = canvas.toDataURL('image/png');
  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  // A4 dimensions in mm
  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 10;
  const headerHeight = 12;
  const footerHeight = 8;
  const contentWidth = pageWidth - margin * 2;
  const contentHeight = pageHeight - margin * 2 - headerHeight - footerHeight;

  const scaledImgHeight = (imgHeight * contentWidth) / imgWidth;
  const totalPages = Math.ceil(scaledImgHeight / contentHeight);

  const pdf = new jsPDF('p', 'mm', 'a4');
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const tickerStr = tickers.join(', ');

  for (let page = 0; page < totalPages; page++) {
    if (page > 0) pdf.addPage();

    // Header
    pdf.setFontSize(8);
    pdf.setTextColor(150, 160, 180);
    pdf.text(`AI Stock Assist — Analysis Report`, margin, margin + 4);
    pdf.text(`${tickerStr} · ${methodology} · ${dateStr}`, pageWidth - margin, margin + 4, { align: 'right' });
    pdf.setDrawColor(30, 41, 59);
    pdf.line(margin, margin + headerHeight - 2, pageWidth - margin, margin + headerHeight - 2);

    // Content slice
    const srcY = page * contentHeight * (imgWidth / contentWidth);
    const srcH = Math.min(contentHeight * (imgWidth / contentWidth), imgHeight - srcY);
    const destH = srcH * (contentWidth / imgWidth);

    // Create a temporary canvas for this page's slice
    const pageCanvas = document.createElement('canvas');
    pageCanvas.width = imgWidth;
    pageCanvas.height = srcH;
    const ctx = pageCanvas.getContext('2d');
    if (ctx) {
      ctx.drawImage(canvas, 0, srcY, imgWidth, srcH, 0, 0, imgWidth, srcH);
      const pageImg = pageCanvas.toDataURL('image/png');
      pdf.addImage(pageImg, 'PNG', margin, margin + headerHeight, contentWidth, destH);
    }

    // Footer
    pdf.setFontSize(7);
    pdf.setTextColor(100, 116, 139);
    pdf.text('Generated by aistockassist.com', margin, pageHeight - margin);
    pdf.text(`Page ${page + 1} of ${totalPages}`, pageWidth - margin, pageHeight - margin, { align: 'right' });
  }

  const filename = `Stock-Analysis-${tickers.join('-')}-${new Date().toISOString().slice(0, 10)}.pdf`;
  pdf.save(filename);
}
