import { ArrowLeft } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

export default function TermsOfService({ onBack }: TermsOfServiceProps) {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-sm text-[var(--color-text-muted)] hover:text-white transition-colors mb-8"
      >
        <ArrowLeft className="w-4 h-4" />
        Back
      </button>

      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-[var(--color-text-muted)] mb-10">Last updated: March 2026</p>

      <div className="space-y-8 text-sm text-[var(--color-text-secondary)] leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using AI Stock Assist ("the Service"), you agree to be bound by these
            Terms of Service. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">2. Description of Service</h2>
          <p>
            AI Stock Assist is an AI-powered stock analysis platform that provides fundamental
            financial metrics, cash flow analysis, and AI-generated BUY/HOLD/SELL recommendations
            using Google Gemini AI. The Service includes stock comparison tools, interactive charts,
            analysis history, and Word document export.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">3. Accounts & Credits</h2>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>You must create an account to use the Service.</li>
            <li>New accounts receive <strong>3 free analyses</strong> to try the Service.</li>
            <li>Additional analyses require purchasing credit packs (one-time purchases, no subscription).</li>
            <li>Each stock ticker analyzed consumes 1 credit. Failed tickers do not consume credits.</li>
            <li>Purchased credits never expire.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">4. Not Financial Advice</h2>
          <p className="font-semibold text-[var(--color-text-primary)] mb-2">
            AI Stock Assist is for educational and informational purposes only.
          </p>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>AI-generated recommendations are <strong>not</strong> financial advice.</li>
            <li>We are not registered financial advisors, brokers, or investment professionals.</li>
            <li>All analysis is based on publicly available financial data and AI interpretation.</li>
            <li>AI models may produce inaccurate, incomplete, or misleading analysis.</li>
            <li>Past performance does not guarantee future results.</li>
            <li><strong>Always do your own research</strong> and consult a qualified financial advisor before making investment decisions.</li>
            <li>We are not responsible for any financial losses resulting from use of the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">5. AI-Generated Content</h2>
          <p>
            All analysis, recommendations, and comparative insights are generated by AI models
            (Google Gemini and Groq Llama). While we strive for accuracy by using real financial
            data from Yahoo Finance, AI-generated content may contain errors, hallucinations,
            or outdated information. You should independently verify any data or recommendations
            before acting on them.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">6. Acceptable Use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or automate access to the Service</li>
            <li>Use bots or automated tools to consume credits or generate analyses</li>
            <li>Share account credentials with others</li>
            <li>Resell or redistribute AI-generated analyses commercially without permission</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">7. Intellectual Property</h2>
          <p className="mb-2">
            AI-generated analyses are provided for your <strong>personal use</strong>. You may:
          </p>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>View, download, and export your analyses</li>
            <li>Share analyses privately for personal research</li>
            <li>Reference analyses in personal investment decisions</li>
          </ul>
          <p className="mt-2 mb-2">You may <strong>not</strong>:</p>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>Resell analyses or present them as professional financial advice</li>
            <li>Use analyses in commercial products or paid services</li>
            <li>Claim AI-generated content as your own original analysis</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">8. Payments & Refunds</h2>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>All payments are processed securely through <strong>Stripe</strong>.</li>
            <li>Credit packs are one-time purchases — no recurring charges.</li>
            <li>Refunds are considered on a case-by-case basis within 30 days of purchase.</li>
            <li>Consumed credits are non-refundable.</li>
            <li>Contact us at the email below for refund requests.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">9. Service Availability</h2>
          <p>
            We strive for high availability but do not guarantee uninterrupted access.
            The Service may be temporarily unavailable due to maintenance, updates, or
            factors beyond our control. We use multiple AI providers (Gemini + Groq) to
            maximize uptime.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">10. Limitation of Liability</h2>
          <p>
            The Service is provided "as is" without warranties of any kind, express or implied.
            To the fullest extent permitted by law, we shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including but not limited
            to financial losses from investment decisions made using this Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">11. Changes to Terms</h2>
          <p>
            We reserve the right to update these Terms of Service at any time. Changes will
            be posted on this page with an updated date. Continued use of the Service after
            changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-[var(--color-text-primary)] mb-3">12. Contact</h2>
          <p>
            Questions about these Terms? Contact us at:{' '}
            <a href="mailto:lindsay.hiebert@gmail.com" className="text-[var(--color-accent)] hover:underline">
              lindsay.hiebert@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
